package zelisline.ub.desktop.license;

import java.security.KeyPair;
import java.security.PrivateKey;
import java.time.Instant;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

import jakarta.validation.constraints.NotBlank;
import lombok.RequiredArgsConstructor;

import zelisline.ub.payments.infrastructure.CredentialEncryptionService;

/**
 * Console-managed desktop license signing key (Super Admin → Platform →
 * Desktop licenses → "License issuer key").
 *
 * <p>Lets a super admin configure license issuance from the console — pasting a
 * key pair generated by {@code backend/scripts/generate-license.sh keys}, or
 * generating a fresh pair here — without touching the deployment environment.
 * The private key is stored encrypted at rest. {@code APP_DESKTOP_LICENSE_PRIVATE_KEY}
 * on the deployment still takes precedence whenever it is set.
 */
@Service
@RequiredArgsConstructor
public class DesktopLicenseIssuerConfigService {

    private static final Logger log = LoggerFactory.getLogger(DesktopLicenseIssuerConfigService.class);

    /** Issuer state shown in the console (private key is never returned). */
    public record IssuerStatus(
            boolean configured,
            /** {@code env} (deployment var wins), {@code console} (stored here), or {@code none}. */
            String source,
            /** Base64 public key recorded with the console-managed key (null when unknown). */
            String publicKey,
            /** When the console-managed key was last saved (null when never). */
            Instant updatedAt,
            /** True when the server has no persistent AES key — console keys become unreadable on restart. */
            boolean encryptionEphemeral
    ) {}

    public record SetIssuerKeyRequest(
            @NotBlank(message = "privateKey is required") String privateKey,
            /** Optional; when present it is checked to form a matching Ed25519 pair. */
            String publicKey
    ) {}

    public record GenerateKeyResult(String publicKey) {}

    private final DesktopLicenseIssuerConfigRepository repository;
    private final CredentialEncryptionService encryptionService;
    private final DesktopLicenseIssuer issuer;

    @Transactional(readOnly = true)
    public IssuerStatus status() {
        DesktopLicenseIssuerConfig row = repository.findById(DesktopLicenseIssuerConfig.SINGLETON_ID).orElse(null);
        String source = issuer.hasEnvKey() ? "env" : (row != null ? "console" : "none");
        return new IssuerStatus(
            issuer.isConfigured(),
            source,
            row == null ? null : row.getPublicKey(),
            row == null ? null : row.getUpdatedAt(),
            encryptionService.usesEphemeralKey()
        );
    }

    /** Stores a signing key pasted from {@code generate-license.sh keys}. */
    @Transactional
    public IssuerStatus setKey(SetIssuerKeyRequest body) {
        String privateKeyBase64 = body.privateKey().trim();
        PrivateKey privateKey = decodePrivateKeyOrThrow(privateKeyBase64);

        String publicKey = blankToNull(body.publicKey());
        if (publicKey != null) {
            verifyPairing(privateKey, publicKey);
        }

        upsert(privateKeyBase64, publicKey);
        log.info(
            "[license-issuer] console signing key updated (public key {}recorded)",
            publicKey == null ? "not " : ""
        );
        return status();
    }

    /** Generates a fresh Ed25519 pair and stores it as the console signing key. */
    @Transactional
    public GenerateKeyResult generate() {
        KeyPair pair = LicenseService.generateKeyPair();
        String privateKeyBase64 = LicenseService.encodePrivateKey(pair.getPrivate());
        String publicKey = LicenseService.encodePublicKey(pair.getPublic());
        upsert(privateKeyBase64, publicKey);
        log.info("[license-issuer] generated a fresh signing key pair via the console");
        return new GenerateKeyResult(publicKey);
    }

    /** Removes the console-managed key (env var still wins if set). */
    @Transactional
    public IssuerStatus clear() {
        repository.deleteById(DesktopLicenseIssuerConfig.SINGLETON_ID);
        log.info("[license-issuer] console signing key removed");
        return status();
    }

    private void upsert(String privateKeyBase64, String publicKey) {
        DesktopLicenseIssuerConfig row = repository
            .findById(DesktopLicenseIssuerConfig.SINGLETON_ID)
            .orElseGet(DesktopLicenseIssuerConfig::new);
        row.setId(DesktopLicenseIssuerConfig.SINGLETON_ID);
        row.setPrivateKeyEnc(encryptionService.encryptSecret(privateKeyBase64));
        row.setPublicKey(publicKey);
        row.setUpdatedAt(Instant.now());
        repository.save(row);
    }

    private static PrivateKey decodePrivateKeyOrThrow(String base64) {
        try {
            return LicenseService.decodePrivateKey(base64);
        } catch (RuntimeException e) {
            throw new ResponseStatusException(
                HttpStatus.BAD_REQUEST,
                "PRIVATE_KEY must be a base64 PKCS#8 Ed25519 key — run backend/scripts/generate-license.sh keys and paste the PRIVATE_KEY line."
            );
        }
    }

    /**
     * Real pairing check: sign a probe token with the private key and verify it
     * with the supplied public key — the same check the till performs.
     */
    private static void verifyPairing(PrivateKey privateKey, String publicKey) {
        LicenseService verifier;
        try {
            verifier = new LicenseService(publicKey);
        } catch (RuntimeException e) {
            throw new ResponseStatusException(
                HttpStatus.BAD_REQUEST,
                "PUBLIC_KEY must be a base64 X.509 Ed25519 public key — paste the PUBLIC_KEY line from generate-license.sh."
            );
        }
        LicensePayload probe = new LicensePayload(
            "__pairing-check__", "free", Instant.now(), Instant.now().plusSeconds(60), null);
        String token = LicenseService.encodeToken(probe, privateKey);
        if (verifier.decodeAndVerify(token) == null) {
            throw new ResponseStatusException(
                HttpStatus.BAD_REQUEST,
                "PRIVATE_KEY and PUBLIC_KEY do not form a matching Ed25519 pair — re-run backend/scripts/generate-license.sh keys and paste both lines together."
            );
        }
        log.info("[license-issuer] pasted PUBLIC_KEY verified against PRIVATE_KEY (matching pair)");
    }

    private static String blankToNull(String s) {
        return s == null || s.isBlank() ? null : s.trim();
    }
}
