package zelisline.ub.desktop.application;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.time.Instant;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Service;

/**
 * Handles the filesystem artefacts the desktop shell checks to decide whether
 * to route to the first‑run wizard ({@code /setup}) or the standard login
 * ({@code /login}).
 *
 * <p>See {@code DESKTOP_INSTALLATION.md} §9 for the wizard flow and §2 for the
 * hardware tier definitions that drive JVM / MariaDB sizing.
 *
 * <h2>Files created</h2>
 * <ul>
 *   <li>{@code ${APP_DATA}/.initialized} — existence tells the shell setup is done</li>
 *   <li>{@code ${APP_DATA}/conf/jvm.opts} — JVM heap flags per hardware tier</li>
 *   <li>{@code ${APP_DATA}/conf/my.cnf} — MariaDB buffer‑pool size per hardware tier</li>
 * </ul>
 */
@Service
@Profile("desktop")
public class DesktopInitializationService {

    private static final Logger log = LoggerFactory.getLogger(DesktopInitializationService.class);

    private final Path appDataDir;

    public DesktopInitializationService(
            @Value("${APP_DATA:${user.home}/.palmart}") String appDataDir) {
        this.appDataDir = Path.of(appDataDir).toAbsolutePath().normalize();
    }

    /**
     * Returns {@code true} when {@code ${APP_DATA}/.initialized} exists.
     * The shell and the root router call this to decide on the startup route.
     */
    public boolean isInitialized() {
        return Files.exists(initializedFile());
    }

    /**
     * Writes all post‑setup artefacts: the {@code .initialized} marker,
     * JVM opts, and MariaDB config for the given hardware tier.
     */
    public void completeInitialization(
            String businessId,
            String hardwareTier,
            Instant setupCompletedAt) throws IOException {

        ensureConfDir();

        writeJvmOpts(hardwareTier);
        writeMyCnf(hardwareTier);
        writeInitializedFile(businessId, setupCompletedAt);

        log.info("[DesktopInit] initialization complete. business={} tier={}",
                businessId, hardwareTier != null ? hardwareTier : "B");
    }

    // ── marker file ────────────────────────────────────────────────────────

    private Path initializedFile() {
        return appDataDir.resolve(".initialized");
    }

    private void writeInitializedFile(String businessId, Instant at) throws IOException {
        String content = String.join("\n",
                "# Palmart desktop — setup completed",
                "# Do not delete this file or the wizard will re-appear.",
                "business_id=" + businessId,
                "setup_completed_at=" + at.toString()
        );
        Files.writeString(initializedFile(), content, StandardCharsets.UTF_8,
                StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
        log.info("[DesktopInit] wrote {}", initializedFile());
    }

    // ── JVM opts ───────────────────────────────────────────────────────────

    private Path jvmOptsFile() {
        return appDataDir.resolve("conf/jvm.opts");
    }

    private void writeJvmOpts(String hardwareTier) throws IOException {
        Tier t = Tier.fromCode(hardwareTier);
        // GC: G1 is the sensible default for a server-style JVM running a
        // monolithic web app. ParallelGC (the throughput collector) is an
        // alternative for single‑till installs with a small heap, but G1
        // avoids the occasional multi‑second stop‑the‑world pauses that
        // make the cashier UI freeze.
        String opts = String.join("\n",
                "# Palmart desktop JVM options — auto-generated by first-run wizard",
                "# Tier: " + t.code + " (" + t.label + ")",
                "# Regenerate by deleting " + appDataDir.resolve(".initialized"),
                "",
                "-Xms" + t.jvmMinHeap,
                "-Xmx" + t.jvmMaxHeap,
                "-XX:+UseG1GC",
                "-XX:MaxGCPauseMillis=200",
                // Let the OS release unused heap back — important on 4–8 GB machines.
                "-XX:+UseTransparentHugePages"
        );
        Files.writeString(jvmOptsFile(), opts, StandardCharsets.UTF_8,
                StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
        log.info("[DesktopInit] wrote {} (heap {}/{})", jvmOptsFile(), t.jvmMinHeap, t.jvmMaxHeap);
    }

    // ── MariaDB config ─────────────────────────────────────────────────────

    private Path myCnfFile() {
        return appDataDir.resolve("conf/my.cnf");
    }

    private void writeMyCnf(String hardwareTier) throws IOException {
        Tier t = Tier.fromCode(hardwareTier);
        // The bundled MariaDB runs on port 33306 with a dedicated datadir
        // under APP_DATA/db. The shell passes these settings via --defaults-file.
        String cnf = String.join("\n",
                "# Palmart desktop MariaDB config — auto-generated by first-run wizard",
                "# Tier: " + t.code + " (" + t.label + ")",
                "# Regenerate by deleting " + appDataDir.resolve(".initialized"),
                "",
                "[mysqld]",
                "innodb_buffer_pool_size = " + t.mariadbBufferPool,
                "innodb_log_file_size = " + t.mariadbLogFileSize,
                "innodb_flush_method = O_DIRECT",
                "innodb_flush_log_at_trx_commit = 2",
                "max_connections = " + t.mariadbMaxConnections,
                "character-set-server = utf8mb4",
                "collation-server = utf8mb4_unicode_ci",
                "port = 33306",
                "bind-address = 127.0.0.1"
        );
        Files.writeString(myCnfFile(), cnf, StandardCharsets.UTF_8,
                StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
        log.info("[DesktopInit] wrote {} (buffer pool {})", myCnfFile(), t.mariadbBufferPool);
    }

    // ── helpers ────────────────────────────────────────────────────────────

    private void ensureConfDir() throws IOException {
        Path conf = appDataDir.resolve("conf");
        Files.createDirectories(conf);
    }

    /**
     * Hardware sizing tiers from {@code DESKTOP_INSTALLATION.md} §2.
     * The shell maps the user's radio‑button choice to a tier letter;
     * this enum turns it into concrete JVM and MariaDB numbers.
     */
    enum Tier {
        A("A", "Single till — light", "256m", "512m", "128M", "64M", "30"),
        B("B", "Single till — full", "512m", "1g", "512M", "128M", "50"),
        C("C", "LAN server", "1g", "2g", "1G", "256M", "100");

        final String code;
        final String label;
        final String jvmMinHeap;
        final String jvmMaxHeap;
        final String mariadbBufferPool;
        final String mariadbLogFileSize;
        final String mariadbMaxConnections;

        Tier(String code, String label, String jvmMinHeap, String jvmMaxHeap,
             String mariadbBufferPool, String mariadbLogFileSize,
             String mariadbMaxConnections) {
            this.code = code;
            this.label = label;
            this.jvmMinHeap = jvmMinHeap;
            this.jvmMaxHeap = jvmMaxHeap;
            this.mariadbBufferPool = mariadbBufferPool;
            this.mariadbLogFileSize = mariadbLogFileSize;
            this.mariadbMaxConnections = mariadbMaxConnections;
        }

        static Tier fromCode(String code) {
            if ("A".equalsIgnoreCase(code)) return A;
            if ("C".equalsIgnoreCase(code)) return C;
            return B; // default: full single-till
        }
    }
}
