-- Super Admin load-test console: tag platform_request_log rows generated by a
-- load test run so Platform → Logs can show load-test traffic separately from
-- real users. The value is the LoadTestService run id (e.g. lt-1750000000000-1).
ALTER TABLE platform_request_log
  ADD COLUMN load_test_run_id CHAR(36) NULL AFTER ip;

CREATE INDEX idx_platform_request_log_load_test
  ON platform_request_log (load_test_run_id, logged_at);
